// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebBirthdayApp.Database;

#nullable disable

namespace WebBirthdayApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240202181200_SeparatingImages")]
    partial class SeparatingImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebBirthdayApp.Models.Image", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasMaxLength(524288)
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Image", (string)null);
                });

            modelBuilder.Entity("WebBirthdayApp.Models.Person", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<int?>("ImgId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ImgId")
                        .IsUnique();

                    b.ToTable("Person", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateOnly(1995, 3, 7),
                            Name = "Юрий",
                            Patronymic = "Дмитриевич",
                            SecondName = "Цветков"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateOnly(1972, 6, 12),
                            Name = "Вера",
                            Patronymic = "Тимофеевна",
                            SecondName = "Соловьева"
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateOnly(1984, 8, 2),
                            Name = "Евгений",
                            Patronymic = "Федорович",
                            SecondName = "Виноградов"
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateOnly(1985, 2, 12),
                            Name = "Галина",
                            Patronymic = "Васильевна",
                            SecondName = "Соловьева"
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateOnly(2003, 9, 25),
                            Name = "Ольга",
                            Patronymic = "Васильевна",
                            SecondName = "Белая"
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateOnly(1980, 7, 16),
                            Name = "Федор",
                            Patronymic = "Валерьевич",
                            SecondName = "Зайцев"
                        },
                        new
                        {
                            Id = 7,
                            Birthday = new DateOnly(1984, 1, 25),
                            Name = "Ольга",
                            Patronymic = "Евгеньевна",
                            SecondName = "Давыдова"
                        },
                        new
                        {
                            Id = 8,
                            Birthday = new DateOnly(1993, 10, 12),
                            Name = "Юрий",
                            Patronymic = "Ярославович",
                            SecondName = "Быков"
                        },
                        new
                        {
                            Id = 9,
                            Birthday = new DateOnly(1965, 7, 17),
                            Name = "Дмитрий",
                            Patronymic = "Олегович",
                            SecondName = "Васильев"
                        },
                        new
                        {
                            Id = 10,
                            Birthday = new DateOnly(1982, 6, 17),
                            Name = "Виктор",
                            Patronymic = "Семёнович",
                            SecondName = "Никитин"
                        },
                        new
                        {
                            Id = 11,
                            Birthday = new DateOnly(1991, 12, 1),
                            Name = "Тамара",
                            Patronymic = "Игоревна",
                            SecondName = "Ефимова"
                        },
                        new
                        {
                            Id = 12,
                            Birthday = new DateOnly(1985, 1, 3),
                            Name = "Светлана",
                            Patronymic = "Евгеньевна",
                            SecondName = "Романова"
                        },
                        new
                        {
                            Id = 13,
                            Birthday = new DateOnly(1965, 9, 21),
                            Name = "Лариса",
                            Patronymic = "Григорьевна",
                            SecondName = "Борисова"
                        },
                        new
                        {
                            Id = 14,
                            Birthday = new DateOnly(2006, 2, 25),
                            Name = "Светлана",
                            Patronymic = "Алексеевна",
                            SecondName = "Зайцева"
                        },
                        new
                        {
                            Id = 15,
                            Birthday = new DateOnly(1969, 8, 9),
                            Name = "Павел",
                            Patronymic = "Юрьевич",
                            SecondName = "Ефимов"
                        },
                        new
                        {
                            Id = 16,
                            Birthday = new DateOnly(1985, 7, 1),
                            Name = "Станислав",
                            Patronymic = "Андреевич",
                            SecondName = "Зайцев"
                        },
                        new
                        {
                            Id = 17,
                            Birthday = new DateOnly(1966, 8, 9),
                            Name = "Виктория",
                            Patronymic = "Ивановна",
                            SecondName = "Маслова"
                        },
                        new
                        {
                            Id = 18,
                            Birthday = new DateOnly(1993, 9, 18),
                            Name = "Олег",
                            Patronymic = "Дмитриевич",
                            SecondName = "Крылов"
                        },
                        new
                        {
                            Id = 19,
                            Birthday = new DateOnly(1978, 9, 23),
                            Name = "Василий",
                            Patronymic = "Николаевич",
                            SecondName = "Кузнецов"
                        },
                        new
                        {
                            Id = 20,
                            Birthday = new DateOnly(1990, 9, 17),
                            Name = "Владимир",
                            Patronymic = "Юрьевич",
                            SecondName = "Борисов"
                        },
                        new
                        {
                            Id = 21,
                            Birthday = new DateOnly(1989, 4, 10),
                            Name = "Станислав",
                            Patronymic = "Викторович",
                            SecondName = "Мухин"
                        },
                        new
                        {
                            Id = 22,
                            Birthday = new DateOnly(1976, 10, 9),
                            Name = "Олег",
                            Patronymic = "Леонидович",
                            SecondName = "Маслов"
                        },
                        new
                        {
                            Id = 23,
                            Birthday = new DateOnly(1973, 9, 13),
                            Name = "Ольга",
                            Patronymic = "Романовна",
                            SecondName = "Кукушкина"
                        },
                        new
                        {
                            Id = 24,
                            Birthday = new DateOnly(1983, 1, 7),
                            Name = "Игорь",
                            Patronymic = "Васильевич",
                            SecondName = "Морозов"
                        },
                        new
                        {
                            Id = 25,
                            Birthday = new DateOnly(1969, 12, 19),
                            Name = "Георгий",
                            Patronymic = "Семёнович",
                            SecondName = "Крылов"
                        },
                        new
                        {
                            Id = 26,
                            Birthday = new DateOnly(2006, 3, 23),
                            Name = "Евгения",
                            Patronymic = "Федоровна",
                            SecondName = "Красная"
                        },
                        new
                        {
                            Id = 27,
                            Birthday = new DateOnly(1974, 7, 18),
                            Name = "София",
                            Patronymic = "Семёновна",
                            SecondName = "Давыдова"
                        },
                        new
                        {
                            Id = 28,
                            Birthday = new DateOnly(1974, 7, 26),
                            Name = "Денис",
                            Patronymic = "Олегович",
                            SecondName = "Цветков"
                        },
                        new
                        {
                            Id = 29,
                            Birthday = new DateOnly(1995, 1, 16),
                            Name = "Людмила",
                            Patronymic = "Анатольевна",
                            SecondName = "Быкова"
                        },
                        new
                        {
                            Id = 30,
                            Birthday = new DateOnly(1978, 10, 21),
                            Name = "Дмитрий",
                            Patronymic = "Дмитриевич",
                            SecondName = "Петров"
                        },
                        new
                        {
                            Id = 31,
                            Birthday = new DateOnly(1987, 9, 4),
                            Name = "Денис",
                            Patronymic = "Олегович",
                            SecondName = "Новиков"
                        },
                        new
                        {
                            Id = 32,
                            Birthday = new DateOnly(1987, 5, 17),
                            Name = "София",
                            Patronymic = "Олеговна",
                            SecondName = "Петухова"
                        },
                        new
                        {
                            Id = 33,
                            Birthday = new DateOnly(1999, 1, 23),
                            Name = "Людмила",
                            Patronymic = "Васильевна",
                            SecondName = "Красная"
                        },
                        new
                        {
                            Id = 34,
                            Birthday = new DateOnly(1990, 10, 21),
                            Name = "Иван",
                            Patronymic = "Сергеевич",
                            SecondName = "Виноградов"
                        },
                        new
                        {
                            Id = 35,
                            Birthday = new DateOnly(2002, 2, 9),
                            Name = "Алина",
                            Patronymic = "Ивановна",
                            SecondName = "Волчица"
                        },
                        new
                        {
                            Id = 36,
                            Birthday = new DateOnly(1978, 2, 14),
                            Name = "Александра",
                            Patronymic = "Ярославовна",
                            SecondName = "Кукушкина"
                        },
                        new
                        {
                            Id = 37,
                            Birthday = new DateOnly(2002, 3, 26),
                            Name = "Михаил",
                            Patronymic = "Анатольевич",
                            SecondName = "Ефимов"
                        },
                        new
                        {
                            Id = 38,
                            Birthday = new DateOnly(1968, 10, 10),
                            Name = "Дмитрий",
                            Patronymic = "Евгеньевич",
                            SecondName = "Егоров"
                        },
                        new
                        {
                            Id = 39,
                            Birthday = new DateOnly(2005, 12, 11),
                            Name = "Михаил",
                            Patronymic = "Павлович",
                            SecondName = "Сидоров"
                        },
                        new
                        {
                            Id = 40,
                            Birthday = new DateOnly(1991, 1, 3),
                            Name = "Игорь",
                            Patronymic = "Владимирович",
                            SecondName = "Борисов"
                        },
                        new
                        {
                            Id = 41,
                            Birthday = new DateOnly(1987, 1, 24),
                            Name = "Тимофей",
                            Patronymic = "Леонидович",
                            SecondName = "Виноградов"
                        },
                        new
                        {
                            Id = 42,
                            Birthday = new DateOnly(1976, 10, 13),
                            Name = "Елена",
                            Patronymic = "Григорьевна",
                            SecondName = "Мухина"
                        },
                        new
                        {
                            Id = 43,
                            Birthday = new DateOnly(1985, 4, 3),
                            Name = "Вера",
                            Patronymic = "Леонидовна",
                            SecondName = "Соловьева"
                        },
                        new
                        {
                            Id = 44,
                            Birthday = new DateOnly(1965, 5, 8),
                            Name = "Евгений",
                            Patronymic = "Андреевич",
                            SecondName = "Сидоров"
                        },
                        new
                        {
                            Id = 45,
                            Birthday = new DateOnly(2006, 6, 9),
                            Name = "Станислав",
                            Patronymic = "Леонидович",
                            SecondName = "Маслов"
                        },
                        new
                        {
                            Id = 46,
                            Birthday = new DateOnly(1968, 4, 16),
                            Name = "Надежда",
                            Patronymic = "Борисовна",
                            SecondName = "Виноградова"
                        },
                        new
                        {
                            Id = 47,
                            Birthday = new DateOnly(1979, 4, 21),
                            Name = "Александра",
                            Patronymic = "Леонидовна",
                            SecondName = "Мухина"
                        },
                        new
                        {
                            Id = 48,
                            Birthday = new DateOnly(2000, 2, 8),
                            Name = "Людмила",
                            Patronymic = "Васильевна",
                            SecondName = "Быкова"
                        },
                        new
                        {
                            Id = 49,
                            Birthday = new DateOnly(1969, 8, 22),
                            Name = "Лариса",
                            Patronymic = "Георгиевна",
                            SecondName = "Соловьева"
                        },
                        new
                        {
                            Id = 50,
                            Birthday = new DateOnly(1970, 5, 15),
                            Name = "Леонид",
                            Patronymic = "Георгиевич",
                            SecondName = "Борисов"
                        },
                        new
                        {
                            Id = 51,
                            Birthday = new DateOnly(1968, 3, 1),
                            Name = "Борис",
                            Patronymic = "Тимофеевич",
                            SecondName = "Никитин"
                        },
                        new
                        {
                            Id = 52,
                            Birthday = new DateOnly(1992, 1, 4),
                            Name = "Андрей",
                            Patronymic = "Леонидович",
                            SecondName = "Морозов"
                        },
                        new
                        {
                            Id = 53,
                            Birthday = new DateOnly(1978, 11, 12),
                            Name = "Михаил",
                            Patronymic = "Иванович",
                            SecondName = "Никитин"
                        },
                        new
                        {
                            Id = 54,
                            Birthday = new DateOnly(1976, 9, 26),
                            Name = "Андрей",
                            Patronymic = "Олегович",
                            SecondName = "Никитин"
                        },
                        new
                        {
                            Id = 55,
                            Birthday = new DateOnly(1976, 11, 7),
                            Name = "Олег",
                            Patronymic = "Иванович",
                            SecondName = "Виноградов"
                        },
                        new
                        {
                            Id = 56,
                            Birthday = new DateOnly(2004, 2, 15),
                            Name = "Наталья",
                            Patronymic = "Владимировна",
                            SecondName = "Красная"
                        },
                        new
                        {
                            Id = 57,
                            Birthday = new DateOnly(2002, 11, 6),
                            Name = "Федор",
                            Patronymic = "Владимирович",
                            SecondName = "Козлов"
                        },
                        new
                        {
                            Id = 58,
                            Birthday = new DateOnly(1971, 2, 3),
                            Name = "Виктория",
                            Patronymic = "Романовна",
                            SecondName = "Смирная"
                        },
                        new
                        {
                            Id = 59,
                            Birthday = new DateOnly(1966, 2, 5),
                            Name = "Зоя",
                            Patronymic = "Григорьевна",
                            SecondName = "Борисова"
                        },
                        new
                        {
                            Id = 60,
                            Birthday = new DateOnly(1968, 9, 21),
                            Name = "Олег",
                            Patronymic = "Григорьевич",
                            SecondName = "Лобанов"
                        },
                        new
                        {
                            Id = 61,
                            Birthday = new DateOnly(1975, 6, 21),
                            Name = "Виктор",
                            Patronymic = "Иванович",
                            SecondName = "Морозов"
                        },
                        new
                        {
                            Id = 62,
                            Birthday = new DateOnly(1978, 10, 10),
                            Name = "Юрий",
                            Patronymic = "Игоревич",
                            SecondName = "Быков"
                        },
                        new
                        {
                            Id = 63,
                            Birthday = new DateOnly(1983, 5, 26),
                            Name = "Юлия",
                            Patronymic = "Игоревна",
                            SecondName = "Белая"
                        },
                        new
                        {
                            Id = 64,
                            Birthday = new DateOnly(1996, 12, 20),
                            Name = "Денис",
                            Patronymic = "Сергеевич",
                            SecondName = "Егоров"
                        },
                        new
                        {
                            Id = 65,
                            Birthday = new DateOnly(1995, 10, 19),
                            Name = "Оксана",
                            Patronymic = "Владимировна",
                            SecondName = "Никитина"
                        },
                        new
                        {
                            Id = 66,
                            Birthday = new DateOnly(1984, 1, 6),
                            Name = "Виктория",
                            Patronymic = "Федоровна",
                            SecondName = "Крылова"
                        },
                        new
                        {
                            Id = 67,
                            Birthday = new DateOnly(2006, 1, 3),
                            Name = "Иван",
                            Patronymic = "Дмитриевич",
                            SecondName = "Белов"
                        },
                        new
                        {
                            Id = 68,
                            Birthday = new DateOnly(1983, 11, 17),
                            Name = "Игорь",
                            Patronymic = "Анатольевич",
                            SecondName = "Маслов"
                        },
                        new
                        {
                            Id = 69,
                            Birthday = new DateOnly(1988, 11, 11),
                            Name = "Сергей",
                            Patronymic = "Станиславович",
                            SecondName = "Соколов"
                        },
                        new
                        {
                            Id = 70,
                            Birthday = new DateOnly(1986, 3, 2),
                            Name = "Дарья",
                            Patronymic = "Андреевна",
                            SecondName = "Маслова"
                        },
                        new
                        {
                            Id = 71,
                            Birthday = new DateOnly(2007, 10, 24),
                            Name = "Павел",
                            Patronymic = "Евгеньевич",
                            SecondName = "Романов"
                        },
                        new
                        {
                            Id = 72,
                            Birthday = new DateOnly(1979, 5, 18),
                            Name = "Алина",
                            Patronymic = "Евгеньевна",
                            SecondName = "Соловьева"
                        },
                        new
                        {
                            Id = 73,
                            Birthday = new DateOnly(1986, 6, 25),
                            Name = "Валерий",
                            Patronymic = "Тимофеевич",
                            SecondName = "Петров"
                        },
                        new
                        {
                            Id = 74,
                            Birthday = new DateOnly(2005, 8, 22),
                            Name = "Виктор",
                            Patronymic = "Ярославович",
                            SecondName = "Копылов"
                        },
                        new
                        {
                            Id = 75,
                            Birthday = new DateOnly(1988, 7, 4),
                            Name = "Оксана",
                            Patronymic = "Романовна",
                            SecondName = "Петухова"
                        },
                        new
                        {
                            Id = 76,
                            Birthday = new DateOnly(1973, 3, 7),
                            Name = "Галина",
                            Patronymic = "Игоревна",
                            SecondName = "Рожкова"
                        },
                        new
                        {
                            Id = 77,
                            Birthday = new DateOnly(1969, 12, 13),
                            Name = "Екатерина",
                            Patronymic = "Николаевна",
                            SecondName = "Красная"
                        },
                        new
                        {
                            Id = 78,
                            Birthday = new DateOnly(2005, 2, 1),
                            Name = "Иван",
                            Patronymic = "Викторович",
                            SecondName = "Волков"
                        },
                        new
                        {
                            Id = 79,
                            Birthday = new DateOnly(1974, 7, 8),
                            Name = "Валентина",
                            Patronymic = "Павловна",
                            SecondName = "Борисова"
                        },
                        new
                        {
                            Id = 80,
                            Birthday = new DateOnly(1969, 10, 23),
                            Name = "Оксана",
                            Patronymic = "Ивановна",
                            SecondName = "Волчица"
                        },
                        new
                        {
                            Id = 81,
                            Birthday = new DateOnly(1976, 2, 8),
                            Name = "Елена",
                            Patronymic = "Федоровна",
                            SecondName = "Рожкова"
                        },
                        new
                        {
                            Id = 82,
                            Birthday = new DateOnly(1987, 8, 17),
                            Name = "Леонид",
                            Patronymic = "Николаевич",
                            SecondName = "Борисов"
                        },
                        new
                        {
                            Id = 83,
                            Birthday = new DateOnly(1969, 9, 11),
                            Name = "Людмила",
                            Patronymic = "Юрьевна",
                            SecondName = "Смирная"
                        },
                        new
                        {
                            Id = 84,
                            Birthday = new DateOnly(1971, 11, 12),
                            Name = "Григорий",
                            Patronymic = "Владимирович",
                            SecondName = "Мухин"
                        },
                        new
                        {
                            Id = 85,
                            Birthday = new DateOnly(1966, 2, 21),
                            Name = "Елена",
                            Patronymic = "Григорьевна",
                            SecondName = "Козлова"
                        },
                        new
                        {
                            Id = 86,
                            Birthday = new DateOnly(2000, 7, 26),
                            Name = "Оксана",
                            Patronymic = "Алексеевна",
                            SecondName = "Давыдова"
                        },
                        new
                        {
                            Id = 87,
                            Birthday = new DateOnly(1987, 4, 3),
                            Name = "Елена",
                            Patronymic = "Леонидовна",
                            SecondName = "Зайцева"
                        },
                        new
                        {
                            Id = 88,
                            Birthday = new DateOnly(1967, 6, 26),
                            Name = "Виктория",
                            Patronymic = "Юрьевна",
                            SecondName = "Попугаева"
                        },
                        new
                        {
                            Id = 89,
                            Birthday = new DateOnly(2001, 2, 14),
                            Name = "Людмила",
                            Patronymic = "Тимофеевна",
                            SecondName = "Маслова"
                        },
                        new
                        {
                            Id = 90,
                            Birthday = new DateOnly(1996, 5, 16),
                            Name = "Борис",
                            Patronymic = "Дмитриевич",
                            SecondName = "Никитин"
                        },
                        new
                        {
                            Id = 91,
                            Birthday = new DateOnly(1974, 6, 1),
                            Name = "София",
                            Patronymic = "Сергеевна",
                            SecondName = "Романова"
                        },
                        new
                        {
                            Id = 92,
                            Birthday = new DateOnly(2007, 7, 24),
                            Name = "Владимир",
                            Patronymic = "Тимофеевич",
                            SecondName = "Романов"
                        },
                        new
                        {
                            Id = 93,
                            Birthday = new DateOnly(1982, 8, 9),
                            Name = "Евгения",
                            Patronymic = "Анатольевна",
                            SecondName = "Белая"
                        },
                        new
                        {
                            Id = 94,
                            Birthday = new DateOnly(1991, 1, 15),
                            Name = "Валерий",
                            Patronymic = "Иванович",
                            SecondName = "Никитин"
                        },
                        new
                        {
                            Id = 95,
                            Birthday = new DateOnly(1967, 10, 11),
                            Name = "Леонид",
                            Patronymic = "Иванович",
                            SecondName = "Краснов"
                        },
                        new
                        {
                            Id = 96,
                            Birthday = new DateOnly(1989, 4, 17),
                            Name = "Тимофей",
                            Patronymic = "Ярославович",
                            SecondName = "Соколов"
                        },
                        new
                        {
                            Id = 97,
                            Birthday = new DateOnly(1988, 7, 19),
                            Name = "Леонид",
                            Patronymic = "Евгеньевич",
                            SecondName = "Мухин"
                        },
                        new
                        {
                            Id = 98,
                            Birthday = new DateOnly(1969, 6, 16),
                            Name = "Денис",
                            Patronymic = "Алексеевич",
                            SecondName = "Борисов"
                        },
                        new
                        {
                            Id = 99,
                            Birthday = new DateOnly(1995, 4, 24),
                            Name = "Дарья",
                            Patronymic = "Николаевна",
                            SecondName = "Быкова"
                        },
                        new
                        {
                            Id = 100,
                            Birthday = new DateOnly(1979, 10, 23),
                            Name = "Сергей",
                            Patronymic = "Иванович",
                            SecondName = "Попов"
                        },
                        new
                        {
                            Id = 101,
                            Birthday = new DateOnly(1992, 10, 3),
                            Name = "Екатерина",
                            Patronymic = "Игоревна",
                            SecondName = "Мухина"
                        },
                        new
                        {
                            Id = 102,
                            Birthday = new DateOnly(1993, 7, 2),
                            Name = "Евгений",
                            Patronymic = "Антонович",
                            SecondName = "Виноградов"
                        },
                        new
                        {
                            Id = 103,
                            Birthday = new DateOnly(1968, 5, 22),
                            Name = "Татьяна",
                            Patronymic = "Алексеевна",
                            SecondName = "Давыдова"
                        },
                        new
                        {
                            Id = 104,
                            Birthday = new DateOnly(2005, 6, 12),
                            Name = "Евгений",
                            Patronymic = "Георгиевич",
                            SecondName = "Крылов"
                        },
                        new
                        {
                            Id = 105,
                            Birthday = new DateOnly(2002, 7, 18),
                            Name = "Инна",
                            Patronymic = "Ярославовна",
                            SecondName = "Соколова"
                        },
                        new
                        {
                            Id = 106,
                            Birthday = new DateOnly(1996, 7, 10),
                            Name = "Юлия",
                            Patronymic = "Тимофеевна",
                            SecondName = "Романова"
                        },
                        new
                        {
                            Id = 107,
                            Birthday = new DateOnly(1984, 12, 12),
                            Name = "Елена",
                            Patronymic = "Романовна",
                            SecondName = "Маслова"
                        },
                        new
                        {
                            Id = 108,
                            Birthday = new DateOnly(1985, 7, 13),
                            Name = "Елена",
                            Patronymic = "Владимировна",
                            SecondName = "Соколова"
                        },
                        new
                        {
                            Id = 109,
                            Birthday = new DateOnly(1979, 10, 25),
                            Name = "Инна",
                            Patronymic = "Ивановна",
                            SecondName = "Ефимова"
                        },
                        new
                        {
                            Id = 110,
                            Birthday = new DateOnly(2007, 5, 2),
                            Name = "Вера",
                            Patronymic = "Федоровна",
                            SecondName = "Цветкова"
                        },
                        new
                        {
                            Id = 111,
                            Birthday = new DateOnly(1966, 1, 6),
                            Name = "Дмитрий",
                            Patronymic = "Федорович",
                            SecondName = "Кузнецов"
                        },
                        new
                        {
                            Id = 112,
                            Birthday = new DateOnly(1971, 2, 9),
                            Name = "Оксана",
                            Patronymic = "Андреевна",
                            SecondName = "Волчица"
                        },
                        new
                        {
                            Id = 113,
                            Birthday = new DateOnly(1973, 3, 25),
                            Name = "Алексей",
                            Patronymic = "Романович",
                            SecondName = "Попов"
                        },
                        new
                        {
                            Id = 114,
                            Birthday = new DateOnly(1976, 4, 4),
                            Name = "Оксана",
                            Patronymic = "Денисовна",
                            SecondName = "Борисова"
                        },
                        new
                        {
                            Id = 115,
                            Birthday = new DateOnly(1967, 7, 14),
                            Name = "Оксана",
                            Patronymic = "Сергеевна",
                            SecondName = "Попугаева"
                        },
                        new
                        {
                            Id = 116,
                            Birthday = new DateOnly(2001, 1, 22),
                            Name = "Мария",
                            Patronymic = "Борисовна",
                            SecondName = "Соловьева"
                        },
                        new
                        {
                            Id = 117,
                            Birthday = new DateOnly(1990, 1, 15),
                            Name = "Василий",
                            Patronymic = "Иванович",
                            SecondName = "Петров"
                        },
                        new
                        {
                            Id = 118,
                            Birthday = new DateOnly(1990, 6, 9),
                            Name = "Анна",
                            Patronymic = "Андреевна",
                            SecondName = "Соловьева"
                        },
                        new
                        {
                            Id = 119,
                            Birthday = new DateOnly(1969, 2, 20),
                            Name = "Ольга",
                            Patronymic = "Сергеевна",
                            SecondName = "Петухова"
                        },
                        new
                        {
                            Id = 120,
                            Birthday = new DateOnly(1966, 9, 26),
                            Name = "Алина",
                            Patronymic = "Валерьевна",
                            SecondName = "Быкова"
                        },
                        new
                        {
                            Id = 121,
                            Birthday = new DateOnly(2006, 9, 4),
                            Name = "Татьяна",
                            Patronymic = "Дмитриевна",
                            SecondName = "Смирная"
                        },
                        new
                        {
                            Id = 122,
                            Birthday = new DateOnly(1980, 8, 5),
                            Name = "Олег",
                            Patronymic = "Игоревич",
                            SecondName = "Борисов"
                        },
                        new
                        {
                            Id = 123,
                            Birthday = new DateOnly(2001, 4, 11),
                            Name = "Елена",
                            Patronymic = "Анатольевна",
                            SecondName = "Виноградова"
                        },
                        new
                        {
                            Id = 124,
                            Birthday = new DateOnly(1965, 1, 14),
                            Name = "Светлана",
                            Patronymic = "Борисовна",
                            SecondName = "Василькова"
                        },
                        new
                        {
                            Id = 125,
                            Birthday = new DateOnly(1983, 8, 10),
                            Name = "Светлана",
                            Patronymic = "Ивановна",
                            SecondName = "Романова"
                        },
                        new
                        {
                            Id = 126,
                            Birthday = new DateOnly(1985, 10, 6),
                            Name = "Вера",
                            Patronymic = "Олеговна",
                            SecondName = "Борисова"
                        },
                        new
                        {
                            Id = 127,
                            Birthday = new DateOnly(1990, 5, 5),
                            Name = "Валерий",
                            Patronymic = "Тимофеевич",
                            SecondName = "Попов"
                        },
                        new
                        {
                            Id = 128,
                            Birthday = new DateOnly(1967, 1, 2),
                            Name = "Елена",
                            Patronymic = "Анатольевна",
                            SecondName = "Василькова"
                        },
                        new
                        {
                            Id = 129,
                            Birthday = new DateOnly(2001, 6, 15),
                            Name = "Алексей",
                            Patronymic = "Романович",
                            SecondName = "Сидоров"
                        },
                        new
                        {
                            Id = 130,
                            Birthday = new DateOnly(1971, 10, 10),
                            Name = "Владимир",
                            Patronymic = "Евгеньевич",
                            SecondName = "Егоров"
                        },
                        new
                        {
                            Id = 131,
                            Birthday = new DateOnly(1992, 11, 8),
                            Name = "Екатерина",
                            Patronymic = "Станиславовна",
                            SecondName = "Василькова"
                        },
                        new
                        {
                            Id = 132,
                            Birthday = new DateOnly(1974, 11, 7),
                            Name = "Борис",
                            Patronymic = "Юрьевич",
                            SecondName = "Смирнов"
                        },
                        new
                        {
                            Id = 133,
                            Birthday = new DateOnly(1969, 1, 5),
                            Name = "Валентина",
                            Patronymic = "Анатольевна",
                            SecondName = "Давыдова"
                        },
                        new
                        {
                            Id = 134,
                            Birthday = new DateOnly(1980, 8, 12),
                            Name = "Мария",
                            Patronymic = "Андреевна",
                            SecondName = "Василькова"
                        },
                        new
                        {
                            Id = 135,
                            Birthday = new DateOnly(1984, 3, 3),
                            Name = "Григорий",
                            Patronymic = "Андреевич",
                            SecondName = "Соколов"
                        },
                        new
                        {
                            Id = 136,
                            Birthday = new DateOnly(1987, 10, 12),
                            Name = "Светлана",
                            Patronymic = "Евгеньевна",
                            SecondName = "Зайцева"
                        },
                        new
                        {
                            Id = 137,
                            Birthday = new DateOnly(1970, 9, 20),
                            Name = "Надежда",
                            Patronymic = "Васильевна",
                            SecondName = "Красная"
                        },
                        new
                        {
                            Id = 138,
                            Birthday = new DateOnly(2004, 12, 11),
                            Name = "Инна",
                            Patronymic = "Игоревна",
                            SecondName = "Соловьева"
                        },
                        new
                        {
                            Id = 139,
                            Birthday = new DateOnly(1982, 12, 8),
                            Name = "Ольга",
                            Patronymic = "Семёновна",
                            SecondName = "Давыдова"
                        },
                        new
                        {
                            Id = 140,
                            Birthday = new DateOnly(1997, 7, 8),
                            Name = "Людмила",
                            Patronymic = "Евгеньевна",
                            SecondName = "Кукушкина"
                        },
                        new
                        {
                            Id = 141,
                            Birthday = new DateOnly(1972, 5, 8),
                            Name = "Виктор",
                            Patronymic = "Романович",
                            SecondName = "Егоров"
                        },
                        new
                        {
                            Id = 142,
                            Birthday = new DateOnly(1972, 8, 4),
                            Name = "Зоя",
                            Patronymic = "Андреевна",
                            SecondName = "Волчица"
                        },
                        new
                        {
                            Id = 143,
                            Birthday = new DateOnly(1998, 12, 6),
                            Name = "Евгений",
                            Patronymic = "Алексеевич",
                            SecondName = "Кузнецов"
                        },
                        new
                        {
                            Id = 144,
                            Birthday = new DateOnly(1970, 9, 6),
                            Name = "Оксана",
                            Patronymic = "Олеговна",
                            SecondName = "Красная"
                        },
                        new
                        {
                            Id = 145,
                            Birthday = new DateOnly(1992, 2, 13),
                            Name = "Наталья",
                            Patronymic = "Сергеевна",
                            SecondName = "Василькова"
                        },
                        new
                        {
                            Id = 146,
                            Birthday = new DateOnly(1965, 4, 16),
                            Name = "Григорий",
                            Patronymic = "Анатольевич",
                            SecondName = "Белов"
                        },
                        new
                        {
                            Id = 147,
                            Birthday = new DateOnly(2000, 1, 9),
                            Name = "Галина",
                            Patronymic = "Анатольевна",
                            SecondName = "Морозова"
                        },
                        new
                        {
                            Id = 148,
                            Birthday = new DateOnly(2006, 3, 21),
                            Name = "Федор",
                            Patronymic = "Иванович",
                            SecondName = "Мухин"
                        },
                        new
                        {
                            Id = 149,
                            Birthday = new DateOnly(1998, 12, 17),
                            Name = "Инна",
                            Patronymic = "Евгеньевна",
                            SecondName = "Новикова"
                        },
                        new
                        {
                            Id = 150,
                            Birthday = new DateOnly(1971, 12, 8),
                            Name = "Юрий",
                            Patronymic = "Владимирович",
                            SecondName = "Новиков"
                        });
                });

            modelBuilder.Entity("WebBirthdayApp.Models.Person", b =>
                {
                    b.HasOne("WebBirthdayApp.Models.Image", "Img")
                        .WithOne()
                        .HasForeignKey("WebBirthdayApp.Models.Person", "ImgId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Img");
                });
#pragma warning restore 612, 618
        }
    }
}
