// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebBirthdayApp.Database;

#nullable disable

namespace WebBirthdayApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240131084745_AddDataToPersonTable")]
    partial class AddDataToPersonTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebBirthdayApp.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Person", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateOnly(1971, 9, 16),
                            Name = "Игорь",
                            Patronymic = "Ярославович",
                            SecondName = "Белов"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateOnly(1971, 5, 3),
                            Name = "Людмила",
                            Patronymic = "Ивановна",
                            SecondName = "Волчица"
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateOnly(1975, 5, 15),
                            Name = "Виктория",
                            Patronymic = "Викторовна",
                            SecondName = "Виноградова"
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateOnly(1994, 1, 8),
                            Name = "Елена",
                            Patronymic = "Евгеньевна",
                            SecondName = "Волчица"
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateOnly(1967, 12, 20),
                            Name = "Станислав",
                            Patronymic = "Павлович",
                            SecondName = "Смирнов"
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateOnly(2001, 9, 15),
                            Name = "Екатерина",
                            Patronymic = "Анатольевна",
                            SecondName = "Зайцева"
                        },
                        new
                        {
                            Id = 7,
                            Birthday = new DateOnly(1994, 9, 3),
                            Name = "Зоя",
                            Patronymic = "Леонидовна",
                            SecondName = "Копылова"
                        },
                        new
                        {
                            Id = 8,
                            Birthday = new DateOnly(1988, 4, 13),
                            Name = "Елена",
                            Patronymic = "Евгеньевна",
                            SecondName = "Соловьева"
                        },
                        new
                        {
                            Id = 9,
                            Birthday = new DateOnly(1986, 3, 3),
                            Name = "Евгения",
                            Patronymic = "Евгеньевна",
                            SecondName = "Василькова"
                        },
                        new
                        {
                            Id = 10,
                            Birthday = new DateOnly(1995, 5, 17),
                            Name = "Анна",
                            Patronymic = "Станиславовна",
                            SecondName = "Борисова"
                        },
                        new
                        {
                            Id = 11,
                            Birthday = new DateOnly(1966, 5, 26),
                            Name = "Станислав",
                            Patronymic = "Георгиевич",
                            SecondName = "Козлов"
                        },
                        new
                        {
                            Id = 12,
                            Birthday = new DateOnly(1975, 8, 10),
                            Name = "Светлана",
                            Patronymic = "Игоревна",
                            SecondName = "Соловьева"
                        },
                        new
                        {
                            Id = 13,
                            Birthday = new DateOnly(1972, 8, 12),
                            Name = "Игорь",
                            Patronymic = "Борисович",
                            SecondName = "Маслов"
                        },
                        new
                        {
                            Id = 14,
                            Birthday = new DateOnly(1966, 8, 10),
                            Name = "Вера",
                            Patronymic = "Олеговна",
                            SecondName = "Смирная"
                        },
                        new
                        {
                            Id = 15,
                            Birthday = new DateOnly(1998, 7, 20),
                            Name = "Григорий",
                            Patronymic = "Дмитриевич",
                            SecondName = "Рожков"
                        },
                        new
                        {
                            Id = 16,
                            Birthday = new DateOnly(2007, 10, 7),
                            Name = "Григорий",
                            Patronymic = "Борисович",
                            SecondName = "Копылов"
                        },
                        new
                        {
                            Id = 17,
                            Birthday = new DateOnly(1995, 7, 17),
                            Name = "Алексей",
                            Patronymic = "Андреевич",
                            SecondName = "Лобанов"
                        },
                        new
                        {
                            Id = 18,
                            Birthday = new DateOnly(1976, 6, 19),
                            Name = "Олег",
                            Patronymic = "Иванович",
                            SecondName = "Романов"
                        },
                        new
                        {
                            Id = 19,
                            Birthday = new DateOnly(1975, 6, 12),
                            Name = "Людмила",
                            Patronymic = "Дмитриевна",
                            SecondName = "Соловьева"
                        },
                        new
                        {
                            Id = 20,
                            Birthday = new DateOnly(1999, 11, 18),
                            Name = "Владимир",
                            Patronymic = "Валерьевич",
                            SecondName = "Васильев"
                        },
                        new
                        {
                            Id = 21,
                            Birthday = new DateOnly(1974, 10, 9),
                            Name = "Борис",
                            Patronymic = "Антонович",
                            SecondName = "Виноградов"
                        },
                        new
                        {
                            Id = 22,
                            Birthday = new DateOnly(1990, 11, 17),
                            Name = "Станислав",
                            Patronymic = "Валерьевич",
                            SecondName = "Соловьев"
                        },
                        new
                        {
                            Id = 23,
                            Birthday = new DateOnly(2007, 4, 4),
                            Name = "Сергей",
                            Patronymic = "Владимирович",
                            SecondName = "Никитин"
                        },
                        new
                        {
                            Id = 24,
                            Birthday = new DateOnly(1985, 1, 25),
                            Name = "Анна",
                            Patronymic = "Владимировна",
                            SecondName = "Смирная"
                        },
                        new
                        {
                            Id = 25,
                            Birthday = new DateOnly(1996, 4, 11),
                            Name = "Юлия",
                            Patronymic = "Николаевна",
                            SecondName = "Петухова"
                        },
                        new
                        {
                            Id = 26,
                            Birthday = new DateOnly(1991, 8, 26),
                            Name = "Светлана",
                            Patronymic = "Евгеньевна",
                            SecondName = "Петухова"
                        },
                        new
                        {
                            Id = 27,
                            Birthday = new DateOnly(1994, 8, 1),
                            Name = "Лариса",
                            Patronymic = "Алексеевна",
                            SecondName = "Попугаева"
                        },
                        new
                        {
                            Id = 28,
                            Birthday = new DateOnly(1989, 10, 8),
                            Name = "Сергей",
                            Patronymic = "Семёнович",
                            SecondName = "Копылов"
                        },
                        new
                        {
                            Id = 29,
                            Birthday = new DateOnly(1970, 7, 13),
                            Name = "Николай",
                            Patronymic = "Иванович",
                            SecondName = "Крылов"
                        },
                        new
                        {
                            Id = 30,
                            Birthday = new DateOnly(1975, 6, 14),
                            Name = "Дмитрий",
                            Patronymic = "Тимофеевич",
                            SecondName = "Лобанов"
                        },
                        new
                        {
                            Id = 31,
                            Birthday = new DateOnly(1998, 6, 26),
                            Name = "Денис",
                            Patronymic = "Олегович",
                            SecondName = "Никитин"
                        },
                        new
                        {
                            Id = 32,
                            Birthday = new DateOnly(1980, 5, 21),
                            Name = "Александра",
                            Patronymic = "Дмитриевна",
                            SecondName = "Виноградова"
                        },
                        new
                        {
                            Id = 33,
                            Birthday = new DateOnly(1976, 2, 25),
                            Name = "Алина",
                            Patronymic = "Романовна",
                            SecondName = "Кукушкина"
                        },
                        new
                        {
                            Id = 34,
                            Birthday = new DateOnly(2006, 10, 10),
                            Name = "Лариса",
                            Patronymic = "Ярославовна",
                            SecondName = "Рожкова"
                        },
                        new
                        {
                            Id = 35,
                            Birthday = new DateOnly(1999, 7, 9),
                            Name = "Юлия",
                            Patronymic = "Игоревна",
                            SecondName = "Ефимова"
                        },
                        new
                        {
                            Id = 36,
                            Birthday = new DateOnly(1991, 10, 7),
                            Name = "Ольга",
                            Patronymic = "Романовна",
                            SecondName = "Романова"
                        },
                        new
                        {
                            Id = 37,
                            Birthday = new DateOnly(2001, 5, 11),
                            Name = "Андрей",
                            Patronymic = "Георгиевич",
                            SecondName = "Смирнов"
                        },
                        new
                        {
                            Id = 38,
                            Birthday = new DateOnly(2007, 11, 23),
                            Name = "Тимофей",
                            Patronymic = "Евгеньевич",
                            SecondName = "Попов"
                        },
                        new
                        {
                            Id = 39,
                            Birthday = new DateOnly(1968, 9, 21),
                            Name = "Олег",
                            Patronymic = "Евгеньевич",
                            SecondName = "Белов"
                        },
                        new
                        {
                            Id = 40,
                            Birthday = new DateOnly(1982, 9, 26),
                            Name = "Лариса",
                            Patronymic = "Георгиевна",
                            SecondName = "Кукушкина"
                        },
                        new
                        {
                            Id = 41,
                            Birthday = new DateOnly(1965, 4, 14),
                            Name = "Марина",
                            Patronymic = "Сергеевна",
                            SecondName = "Маслова"
                        },
                        new
                        {
                            Id = 42,
                            Birthday = new DateOnly(1978, 4, 9),
                            Name = "Борис",
                            Patronymic = "Юрьевич",
                            SecondName = "Новиков"
                        },
                        new
                        {
                            Id = 43,
                            Birthday = new DateOnly(2002, 2, 18),
                            Name = "Тамара",
                            Patronymic = "Викторовна",
                            SecondName = "Никитина"
                        },
                        new
                        {
                            Id = 44,
                            Birthday = new DateOnly(1973, 5, 23),
                            Name = "Федор",
                            Patronymic = "Владимирович",
                            SecondName = "Соловьев"
                        },
                        new
                        {
                            Id = 45,
                            Birthday = new DateOnly(1999, 12, 12),
                            Name = "Ольга",
                            Patronymic = "Андреевна",
                            SecondName = "Цветкова"
                        },
                        new
                        {
                            Id = 46,
                            Birthday = new DateOnly(1993, 1, 14),
                            Name = "Анна",
                            Patronymic = "Валерьевна",
                            SecondName = "Маслова"
                        },
                        new
                        {
                            Id = 47,
                            Birthday = new DateOnly(2002, 8, 12),
                            Name = "Елена",
                            Patronymic = "Георгиевна",
                            SecondName = "Копылова"
                        },
                        new
                        {
                            Id = 48,
                            Birthday = new DateOnly(1985, 3, 6),
                            Name = "София",
                            Patronymic = "Ивановна",
                            SecondName = "Борисова"
                        },
                        new
                        {
                            Id = 49,
                            Birthday = new DateOnly(2007, 6, 13),
                            Name = "Анатолий",
                            Patronymic = "Федорович",
                            SecondName = "Соколов"
                        },
                        new
                        {
                            Id = 50,
                            Birthday = new DateOnly(1985, 11, 26),
                            Name = "Тамара",
                            Patronymic = "Романовна",
                            SecondName = "Петухова"
                        },
                        new
                        {
                            Id = 51,
                            Birthday = new DateOnly(1970, 3, 10),
                            Name = "Денис",
                            Patronymic = "Романович",
                            SecondName = "Белов"
                        },
                        new
                        {
                            Id = 52,
                            Birthday = new DateOnly(1971, 4, 5),
                            Name = "Анна",
                            Patronymic = "Евгеньевна",
                            SecondName = "Козлова"
                        },
                        new
                        {
                            Id = 53,
                            Birthday = new DateOnly(2004, 12, 18),
                            Name = "Олег",
                            Patronymic = "Анатольевич",
                            SecondName = "Цветков"
                        },
                        new
                        {
                            Id = 54,
                            Birthday = new DateOnly(1982, 5, 17),
                            Name = "Олег",
                            Patronymic = "Игоревич",
                            SecondName = "Борисов"
                        },
                        new
                        {
                            Id = 55,
                            Birthday = new DateOnly(1983, 10, 5),
                            Name = "Юрий",
                            Patronymic = "Евгеньевич",
                            SecondName = "Крылов"
                        },
                        new
                        {
                            Id = 56,
                            Birthday = new DateOnly(2006, 3, 2),
                            Name = "Тамара",
                            Patronymic = "Ярославовна",
                            SecondName = "Смирная"
                        },
                        new
                        {
                            Id = 57,
                            Birthday = new DateOnly(1977, 9, 4),
                            Name = "Дмитрий",
                            Patronymic = "Алексеевич",
                            SecondName = "Егоров"
                        },
                        new
                        {
                            Id = 58,
                            Birthday = new DateOnly(2002, 5, 20),
                            Name = "Виктор",
                            Patronymic = "Иванович",
                            SecondName = "Крылов"
                        },
                        new
                        {
                            Id = 59,
                            Birthday = new DateOnly(1971, 1, 12),
                            Name = "Мария",
                            Patronymic = "Евгеньевна",
                            SecondName = "Ефимова"
                        },
                        new
                        {
                            Id = 60,
                            Birthday = new DateOnly(1986, 8, 26),
                            Name = "Денис",
                            Patronymic = "Георгиевич",
                            SecondName = "Сидоров"
                        },
                        new
                        {
                            Id = 61,
                            Birthday = new DateOnly(1980, 8, 3),
                            Name = "Галина",
                            Patronymic = "Григорьевна",
                            SecondName = "Соловьева"
                        },
                        new
                        {
                            Id = 62,
                            Birthday = new DateOnly(1984, 10, 23),
                            Name = "Юлия",
                            Patronymic = "Евгеньевна",
                            SecondName = "Зайцева"
                        },
                        new
                        {
                            Id = 63,
                            Birthday = new DateOnly(1999, 8, 16),
                            Name = "Дарья",
                            Patronymic = "Денисовна",
                            SecondName = "Зайцева"
                        },
                        new
                        {
                            Id = 64,
                            Birthday = new DateOnly(1965, 1, 3),
                            Name = "Валентина",
                            Patronymic = "Алексеевна",
                            SecondName = "Кукушкина"
                        },
                        new
                        {
                            Id = 65,
                            Birthday = new DateOnly(1976, 8, 11),
                            Name = "Анатолий",
                            Patronymic = "Андреевич",
                            SecondName = "Васильев"
                        },
                        new
                        {
                            Id = 66,
                            Birthday = new DateOnly(2000, 7, 7),
                            Name = "Виктор",
                            Patronymic = "Борисович",
                            SecondName = "Петров"
                        },
                        new
                        {
                            Id = 67,
                            Birthday = new DateOnly(1966, 8, 6),
                            Name = "Анатолий",
                            Patronymic = "Семёнович",
                            SecondName = "Борисов"
                        },
                        new
                        {
                            Id = 68,
                            Birthday = new DateOnly(1983, 1, 19),
                            Name = "Галина",
                            Patronymic = "Евгеньевна",
                            SecondName = "Рожкова"
                        },
                        new
                        {
                            Id = 69,
                            Birthday = new DateOnly(2002, 12, 16),
                            Name = "Федор",
                            Patronymic = "Сергеевич",
                            SecondName = "Никитин"
                        },
                        new
                        {
                            Id = 70,
                            Birthday = new DateOnly(1965, 12, 1),
                            Name = "Антон",
                            Patronymic = "Олегович",
                            SecondName = "Мухин"
                        },
                        new
                        {
                            Id = 71,
                            Birthday = new DateOnly(1997, 5, 5),
                            Name = "Инна",
                            Patronymic = "Анатольевна",
                            SecondName = "Мухина"
                        },
                        new
                        {
                            Id = 72,
                            Birthday = new DateOnly(1985, 6, 21),
                            Name = "Виктория",
                            Patronymic = "Григорьевна",
                            SecondName = "Соловьева"
                        },
                        new
                        {
                            Id = 73,
                            Birthday = new DateOnly(1982, 12, 17),
                            Name = "Юлия",
                            Patronymic = "Олеговна",
                            SecondName = "Василькова"
                        },
                        new
                        {
                            Id = 74,
                            Birthday = new DateOnly(1994, 2, 1),
                            Name = "Ольга",
                            Patronymic = "Дмитриевна",
                            SecondName = "Мухина"
                        },
                        new
                        {
                            Id = 75,
                            Birthday = new DateOnly(1982, 1, 16),
                            Name = "Валентина",
                            Patronymic = "Сергеевна",
                            SecondName = "Новикова"
                        },
                        new
                        {
                            Id = 76,
                            Birthday = new DateOnly(1987, 11, 22),
                            Name = "Людмила",
                            Patronymic = "Евгеньевна",
                            SecondName = "Ефимова"
                        },
                        new
                        {
                            Id = 77,
                            Birthday = new DateOnly(1994, 2, 1),
                            Name = "Евгений",
                            Patronymic = "Семёнович",
                            SecondName = "Ефимов"
                        },
                        new
                        {
                            Id = 78,
                            Birthday = new DateOnly(2005, 12, 3),
                            Name = "Елена",
                            Patronymic = "Юрьевна",
                            SecondName = "Романова"
                        },
                        new
                        {
                            Id = 79,
                            Birthday = new DateOnly(1970, 5, 24),
                            Name = "Валентина",
                            Patronymic = "Дмитриевна",
                            SecondName = "Красная"
                        },
                        new
                        {
                            Id = 80,
                            Birthday = new DateOnly(1999, 1, 23),
                            Name = "Станислав",
                            Patronymic = "Станиславович",
                            SecondName = "Зайцев"
                        },
                        new
                        {
                            Id = 81,
                            Birthday = new DateOnly(1967, 6, 4),
                            Name = "Мария",
                            Patronymic = "Ивановна",
                            SecondName = "Козлова"
                        },
                        new
                        {
                            Id = 82,
                            Birthday = new DateOnly(1965, 4, 10),
                            Name = "Иван",
                            Patronymic = "Ярославович",
                            SecondName = "Козлов"
                        },
                        new
                        {
                            Id = 83,
                            Birthday = new DateOnly(2007, 8, 7),
                            Name = "Александра",
                            Patronymic = "Ярославовна",
                            SecondName = "Соколова"
                        },
                        new
                        {
                            Id = 84,
                            Birthday = new DateOnly(1985, 10, 18),
                            Name = "Николай",
                            Patronymic = "Владимирович",
                            SecondName = "Цветков"
                        },
                        new
                        {
                            Id = 85,
                            Birthday = new DateOnly(1981, 12, 14),
                            Name = "Ольга",
                            Patronymic = "Николаевна",
                            SecondName = "Давыдова"
                        },
                        new
                        {
                            Id = 86,
                            Birthday = new DateOnly(1987, 5, 8),
                            Name = "Наталья",
                            Patronymic = "Сергеевна",
                            SecondName = "Крылова"
                        },
                        new
                        {
                            Id = 87,
                            Birthday = new DateOnly(1993, 6, 7),
                            Name = "Денис",
                            Patronymic = "Валерьевич",
                            SecondName = "Козлов"
                        },
                        new
                        {
                            Id = 88,
                            Birthday = new DateOnly(1994, 12, 2),
                            Name = "Николай",
                            Patronymic = "Иванович",
                            SecondName = "Рожков"
                        },
                        new
                        {
                            Id = 89,
                            Birthday = new DateOnly(1978, 7, 11),
                            Name = "Владимир",
                            Patronymic = "Олегович",
                            SecondName = "Борисов"
                        },
                        new
                        {
                            Id = 90,
                            Birthday = new DateOnly(1973, 10, 13),
                            Name = "Анатолий",
                            Patronymic = "Георгиевич",
                            SecondName = "Соколов"
                        },
                        new
                        {
                            Id = 91,
                            Birthday = new DateOnly(2005, 4, 17),
                            Name = "Павел",
                            Patronymic = "Игоревич",
                            SecondName = "Копылов"
                        },
                        new
                        {
                            Id = 92,
                            Birthday = new DateOnly(1978, 6, 19),
                            Name = "Олег",
                            Patronymic = "Леонидович",
                            SecondName = "Васильев"
                        },
                        new
                        {
                            Id = 93,
                            Birthday = new DateOnly(1967, 8, 14),
                            Name = "Олег",
                            Patronymic = "Иванович",
                            SecondName = "Соколов"
                        },
                        new
                        {
                            Id = 94,
                            Birthday = new DateOnly(1966, 11, 18),
                            Name = "Дмитрий",
                            Patronymic = "Сергеевич",
                            SecondName = "Сидоров"
                        },
                        new
                        {
                            Id = 95,
                            Birthday = new DateOnly(1982, 4, 21),
                            Name = "Тамара",
                            Patronymic = "Григорьевна",
                            SecondName = "Рожкова"
                        },
                        new
                        {
                            Id = 96,
                            Birthday = new DateOnly(1971, 8, 16),
                            Name = "Галина",
                            Patronymic = "Николаевна",
                            SecondName = "Зайцева"
                        },
                        new
                        {
                            Id = 97,
                            Birthday = new DateOnly(1979, 9, 3),
                            Name = "Оксана",
                            Patronymic = "Ярославовна",
                            SecondName = "Зайцева"
                        },
                        new
                        {
                            Id = 98,
                            Birthday = new DateOnly(1979, 5, 8),
                            Name = "Валентина",
                            Patronymic = "Денисовна",
                            SecondName = "Смирная"
                        },
                        new
                        {
                            Id = 99,
                            Birthday = new DateOnly(1989, 11, 26),
                            Name = "Иван",
                            Patronymic = "Борисович",
                            SecondName = "Лобанов"
                        },
                        new
                        {
                            Id = 100,
                            Birthday = new DateOnly(1982, 3, 20),
                            Name = "Сергей",
                            Patronymic = "Романович",
                            SecondName = "Быков"
                        },
                        new
                        {
                            Id = 101,
                            Birthday = new DateOnly(1996, 10, 21),
                            Name = "Виктор",
                            Patronymic = "Евгеньевич",
                            SecondName = "Копылов"
                        },
                        new
                        {
                            Id = 102,
                            Birthday = new DateOnly(1984, 11, 25),
                            Name = "Инна",
                            Patronymic = "Олеговна",
                            SecondName = "Рожкова"
                        },
                        new
                        {
                            Id = 103,
                            Birthday = new DateOnly(1979, 11, 25),
                            Name = "Александра",
                            Patronymic = "Ивановна",
                            SecondName = "Красная"
                        },
                        new
                        {
                            Id = 104,
                            Birthday = new DateOnly(1990, 10, 10),
                            Name = "Алина",
                            Patronymic = "Георгиевна",
                            SecondName = "Красная"
                        },
                        new
                        {
                            Id = 105,
                            Birthday = new DateOnly(2005, 7, 9),
                            Name = "Олег",
                            Patronymic = "Ярославович",
                            SecondName = "Романов"
                        },
                        new
                        {
                            Id = 106,
                            Birthday = new DateOnly(1981, 9, 15),
                            Name = "Анна",
                            Patronymic = "Николаевна",
                            SecondName = "Кукушкина"
                        },
                        new
                        {
                            Id = 107,
                            Birthday = new DateOnly(1999, 6, 21),
                            Name = "Екатерина",
                            Patronymic = "Григорьевна",
                            SecondName = "Мухина"
                        },
                        new
                        {
                            Id = 108,
                            Birthday = new DateOnly(1985, 8, 2),
                            Name = "Татьяна",
                            Patronymic = "Игоревна",
                            SecondName = "Мухина"
                        },
                        new
                        {
                            Id = 109,
                            Birthday = new DateOnly(2004, 12, 23),
                            Name = "Александра",
                            Patronymic = "Георгиевна",
                            SecondName = "Попугаева"
                        },
                        new
                        {
                            Id = 110,
                            Birthday = new DateOnly(1981, 8, 9),
                            Name = "Павел",
                            Patronymic = "Ярославович",
                            SecondName = "Волков"
                        },
                        new
                        {
                            Id = 111,
                            Birthday = new DateOnly(1996, 8, 8),
                            Name = "Иван",
                            Patronymic = "Семёнович",
                            SecondName = "Цветков"
                        },
                        new
                        {
                            Id = 112,
                            Birthday = new DateOnly(2006, 7, 1),
                            Name = "Галина",
                            Patronymic = "Валерьевна",
                            SecondName = "Соловьева"
                        },
                        new
                        {
                            Id = 113,
                            Birthday = new DateOnly(2004, 7, 9),
                            Name = "Виктория",
                            Patronymic = "Игоревна",
                            SecondName = "Попугаева"
                        },
                        new
                        {
                            Id = 114,
                            Birthday = new DateOnly(2007, 2, 23),
                            Name = "Зоя",
                            Patronymic = "Игоревна",
                            SecondName = "Соловьева"
                        },
                        new
                        {
                            Id = 115,
                            Birthday = new DateOnly(1974, 6, 19),
                            Name = "Оксана",
                            Patronymic = "Юрьевна",
                            SecondName = "Лобанова"
                        },
                        new
                        {
                            Id = 116,
                            Birthday = new DateOnly(1991, 2, 20),
                            Name = "Иван",
                            Patronymic = "Сергеевич",
                            SecondName = "Волков"
                        },
                        new
                        {
                            Id = 117,
                            Birthday = new DateOnly(1974, 10, 14),
                            Name = "Ирина",
                            Patronymic = "Денисовна",
                            SecondName = "Петухова"
                        },
                        new
                        {
                            Id = 118,
                            Birthday = new DateOnly(1990, 5, 26),
                            Name = "Ярослав",
                            Patronymic = "Дмитриевич",
                            SecondName = "Белов"
                        },
                        new
                        {
                            Id = 119,
                            Birthday = new DateOnly(1970, 12, 3),
                            Name = "София",
                            Patronymic = "Андреевна",
                            SecondName = "Цветкова"
                        },
                        new
                        {
                            Id = 120,
                            Birthday = new DateOnly(1975, 12, 8),
                            Name = "Владимир",
                            Patronymic = "Павлович",
                            SecondName = "Кузнецов"
                        },
                        new
                        {
                            Id = 121,
                            Birthday = new DateOnly(1993, 3, 3),
                            Name = "Александра",
                            Patronymic = "Денисовна",
                            SecondName = "Копылова"
                        },
                        new
                        {
                            Id = 122,
                            Birthday = new DateOnly(1995, 8, 25),
                            Name = "Николай",
                            Patronymic = "Евгеньевич",
                            SecondName = "Соловьев"
                        },
                        new
                        {
                            Id = 123,
                            Birthday = new DateOnly(2002, 2, 9),
                            Name = "Олег",
                            Patronymic = "Романович",
                            SecondName = "Копылов"
                        },
                        new
                        {
                            Id = 124,
                            Birthday = new DateOnly(2007, 10, 5),
                            Name = "Тимофей",
                            Patronymic = "Романович",
                            SecondName = "Быков"
                        },
                        new
                        {
                            Id = 125,
                            Birthday = new DateOnly(1972, 3, 22),
                            Name = "Олег",
                            Patronymic = "Алексеевич",
                            SecondName = "Романов"
                        },
                        new
                        {
                            Id = 126,
                            Birthday = new DateOnly(1967, 12, 20),
                            Name = "Мария",
                            Patronymic = "Георгиевна",
                            SecondName = "Соколова"
                        },
                        new
                        {
                            Id = 127,
                            Birthday = new DateOnly(1979, 6, 4),
                            Name = "Роман",
                            Patronymic = "Георгиевич",
                            SecondName = "Ефимов"
                        },
                        new
                        {
                            Id = 128,
                            Birthday = new DateOnly(1980, 2, 16),
                            Name = "Светлана",
                            Patronymic = "Денисовна",
                            SecondName = "Морозова"
                        },
                        new
                        {
                            Id = 129,
                            Birthday = new DateOnly(1999, 9, 6),
                            Name = "Алексей",
                            Patronymic = "Тимофеевич",
                            SecondName = "Волков"
                        },
                        new
                        {
                            Id = 130,
                            Birthday = new DateOnly(1979, 7, 20),
                            Name = "Сергей",
                            Patronymic = "Павлович",
                            SecondName = "Зайцев"
                        },
                        new
                        {
                            Id = 131,
                            Birthday = new DateOnly(2007, 9, 2),
                            Name = "Николай",
                            Patronymic = "Иванович",
                            SecondName = "Копылов"
                        },
                        new
                        {
                            Id = 132,
                            Birthday = new DateOnly(1991, 3, 8),
                            Name = "Ольга",
                            Patronymic = "Леонидовна",
                            SecondName = "Красная"
                        },
                        new
                        {
                            Id = 133,
                            Birthday = new DateOnly(2006, 7, 12),
                            Name = "Галина",
                            Patronymic = "Викторовна",
                            SecondName = "Василькова"
                        },
                        new
                        {
                            Id = 134,
                            Birthday = new DateOnly(2006, 1, 23),
                            Name = "Ирина",
                            Patronymic = "Григорьевна",
                            SecondName = "Морозова"
                        },
                        new
                        {
                            Id = 135,
                            Birthday = new DateOnly(1998, 2, 10),
                            Name = "Сергей",
                            Patronymic = "Олегович",
                            SecondName = "Лобанов"
                        },
                        new
                        {
                            Id = 136,
                            Birthday = new DateOnly(1977, 8, 1),
                            Name = "Виктор",
                            Patronymic = "Игоревич",
                            SecondName = "Краснов"
                        },
                        new
                        {
                            Id = 137,
                            Birthday = new DateOnly(2000, 5, 21),
                            Name = "Елена",
                            Patronymic = "Ярославовна",
                            SecondName = "Маслова"
                        },
                        new
                        {
                            Id = 138,
                            Birthday = new DateOnly(1997, 8, 22),
                            Name = "София",
                            Patronymic = "Дмитриевна",
                            SecondName = "Василькова"
                        },
                        new
                        {
                            Id = 139,
                            Birthday = new DateOnly(1981, 10, 3),
                            Name = "Федор",
                            Patronymic = "Андреевич",
                            SecondName = "Сидоров"
                        },
                        new
                        {
                            Id = 140,
                            Birthday = new DateOnly(1975, 9, 20),
                            Name = "Алина",
                            Patronymic = "Евгеньевна",
                            SecondName = "Василькова"
                        },
                        new
                        {
                            Id = 141,
                            Birthday = new DateOnly(1975, 10, 1),
                            Name = "София",
                            Patronymic = "Ивановна",
                            SecondName = "Лобанова"
                        },
                        new
                        {
                            Id = 142,
                            Birthday = new DateOnly(1987, 4, 25),
                            Name = "Юрий",
                            Patronymic = "Ярославович",
                            SecondName = "Соколов"
                        },
                        new
                        {
                            Id = 143,
                            Birthday = new DateOnly(1993, 12, 20),
                            Name = "Андрей",
                            Patronymic = "Владимирович",
                            SecondName = "Виноградов"
                        },
                        new
                        {
                            Id = 144,
                            Birthday = new DateOnly(1970, 9, 11),
                            Name = "Тимофей",
                            Patronymic = "Иванович",
                            SecondName = "Никитин"
                        },
                        new
                        {
                            Id = 145,
                            Birthday = new DateOnly(1980, 2, 22),
                            Name = "Ярослав",
                            Patronymic = "Евгеньевич",
                            SecondName = "Соколов"
                        },
                        new
                        {
                            Id = 146,
                            Birthday = new DateOnly(2001, 9, 8),
                            Name = "Сергей",
                            Patronymic = "Евгеньевич",
                            SecondName = "Маслов"
                        },
                        new
                        {
                            Id = 147,
                            Birthday = new DateOnly(1997, 10, 18),
                            Name = "Мария",
                            Patronymic = "Тимофеевна",
                            SecondName = "Василькова"
                        },
                        new
                        {
                            Id = 148,
                            Birthday = new DateOnly(1986, 4, 12),
                            Name = "Тамара",
                            Patronymic = "Васильевна",
                            SecondName = "Ефимова"
                        },
                        new
                        {
                            Id = 149,
                            Birthday = new DateOnly(2007, 10, 1),
                            Name = "Виктор",
                            Patronymic = "Павлович",
                            SecondName = "Рожков"
                        },
                        new
                        {
                            Id = 150,
                            Birthday = new DateOnly(2002, 5, 10),
                            Name = "Тимофей",
                            Patronymic = "Романович",
                            SecondName = "Копылов"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
